export const REQUEST_CHARACTERS = "REQUEST_CHARACTERS";
export const REQUEST_CHARACTERS_SUCCESS = "REQUEST_CHARACTERS_SUCCESS";
export const REQUEST_CHARACTERS_FAILURE = "REQUEST_CHARACTERS_FAILURE";

export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS";
export const CREATE_CHARACTER_FAILURE = "CREATE_CHARACTER_FAILURE";

export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const REMOVE_CHARACTER_SUCCESS = "REMOVE_CHARACTER_SUCCESS";
export const REMOVE_CHARACTER_FAILURE = "REMOVE_CHARACTER_FAILURE";

export const SET_CHARACTERS_FILTERS = "SET_CHARACTERS_FILTERS";
export const SET_PAGE = "SET_PAGE";

export const REQUEST_SPECIES = "REQUEST_SPECIES";
export const REQUEST_SPECIES_SUCCESS = "REQUEST_SPECIES_SUCCESS";
export const REQUEST_SPECIES_FAILURE = "REQUEST_SPECIES_FAILURE";
